blank_issues_enabled: false
contact_links:
  - name: 📖 Dokumentasi & Panduan
    url: https://github.com/devPSA-Business/PSA-Business-Suite/wiki
    about: Baca panduan penggunaan aplikasi terlebih dahulu
