name: Feature Request
description: Usulkan fitur baru untuk aplikasi
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Deskripsi Fitur
      description: Jelaskan fitur yang diusulkan.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Use Case / Langkah Penggunaan
      description: Bagaimana pengguna akan berinteraksi dengan fitur ini?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Apa hasil akhir yang diharapkan dari fitur ini?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Kriteria agar fitur ini dianggap selesai.
    validations:
      required: true
