export const NavigationMap: Record<string, string> = {
  '/workspace': '/',
  '/office': '/',
  '/settings': '/',
  '/cashier': '/workspace',
  '/dashboard': '/office',
  '/audit': '/office',
  '/office/sync-status': '/office',
  '/finance': '/office',
  '/service-pos': '/workspace',
  '/buyback': '/workspace',
  '/gold-buyback-sales': '/workspace',
  '/inventory': '/workspace',
  '/receive-stock': '/inventory',
  '/barcode-print': '/inventory',
  '/services': '/workspace',
  '/shift': '/workspace',
  '/handover': '/shift',
  '/system-test': '/office',
  '/employees': '/office',
  '/customers': '/office',
  '/settings/printer': '/settings',
  '/settings/receipt': '/settings',
};
